version: "2.2"

services:
    db:
        image: containerregistryalexandrukovacs30244.azurecr.io/db:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=energy-utility-platform
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root

    backend:
        image: containerregistryalexandrukovacs30244.azurecr.io/alexandrukovacs30244backend:latest
        ports:
            - "8080:8080"
        environment:
            - DB_URL=db
        links:
            - db

    frontend:
        image: containerregistryalexandrukovacs30244.azurecr.io/alexandrukovacs30244frontend:latest
        ports:
            - "4200:80"
