version: "2.2"

services:
    db:
        image: containerregistryalexandrukovacs30244.azurecr.io/db:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=energy-utility-platform
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root

    backend:
        image: containerregistryalexandrukovacs30244.azurecr.io/alexandrukovacs30244backend:latest
        # image: backend
        ports:
            # - "8081:8080"
            - '9090:9090'
        environment:
            - DB_URL=db
        links:
            - db

    frontend:
        image: containerregistryalexandrukovacs30244.azurecr.io/alexandrukovacs30244frontend:latest
        # image: frontend
        # ports:
        #     - "4200:80"
        # volumes:
        #     - ./frontend.conf:/etc/nginx/nginx.conf
    
    grpc-proxy:
        image: containerregistryalexandrukovacs30244.azurecr.io/grpc-proxy:latest
        ports:
            - '9901:9901'
            - '9091:9091'
        # volumes:
        #   - ./envoy.yml:/etc/envoy/envoy.yaml
        extra_hosts:
            - host.docker.internal:host-gateway

    reverse:
        image: containerregistryalexandrukovacs30244.azurecr.io/proxy
        ports:
            - 81:80
            - 443:443
        volumes:
            - ./proxy.conf:/etc/nginx/nginx.conf
        links:
            - frontend
            - backend
