version: "1.0"

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=energy-utility-platform
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root

    backend:
        image: backend
        build: ./energy-utility-platform-backend
        ports:
            - "8080:8080"
        environment:
            - DB_URL=db
        links:
            - db

    frontend:
        image: frontend
        build: ./energy-utility-platform-frontend
        ports:
            - "8081:80"
