version: "1.0"

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=energy-utility-platform
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "15672:15672" # manager
            - "5672:5672"   # mq

    backend:
        image: backend
        build: ./energy-utility-platform-backend
        ports:
            - "8080:8080"
        environment:
            - DB_URL=db
            - RABBITMQ_HOST=rabbitmq
        links:
            - db
            - rabbitmq

    frontend:
        image: frontend
        build: ./energy-utility-platform-frontend
        ports:
            - "4200:80"
